kind: Service
apiVersion: v1
metadata:
  name: loyaltyservice
  labels:
    app: loyaltyservice
spec:
  selector:
    app: loyaltyservice
  ports:
  - protocol: TCP
    port: 8280
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyaltyservice
  labels:
    app: loyaltyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyaltyservice
  template:
    metadata:
      labels:
        app: loyaltyservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "loyaltyservice"
        dapr.io/port: "80"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: loyaltyservice
        image: xpiritbv/dapr-demo-loyaltyservice:43980337
        ports:
        - containerPort: 80
        imagePullPolicy: Always