kind: Service
apiVersion: v1
metadata:
  name: orderapi
  labels:
    app: orderapi
spec:
  selector:
    app: orderapi
  ports:
  - protocol: TCP
    port: 8180
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapi
  labels:
    app: orderapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "orderapi"
        dapr.io/port: "80"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: orderapi
        image: xpiritbv/dapr-demo-orderapi:latest
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        ports:
        - containerPort: 80
        imagePullPolicy: Always