kind: Service
apiVersion: v1
metadata:
  name: ordergenerator
  labels:
    app: ordergenerator
spec:
  selector:
    app: ordergenerator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordergenerator
  labels:
    app: ordergenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordergenerator
  template:
    metadata:
      labels:
        app: ordergenerator
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "ordergenerator"
        dapr.io/port: "80"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: ordergenerator
        image: xpiritbv/dapr-demo-ordergenerator:44557753
        ports:
        - containerPort: 80
        imagePullPolicy: Always