kind: Service
apiVersion: v1
metadata:
  name: shippingcostsservice
  labels:
    app: shippingcostsservice
spec:
  selector:
    app: shippingcostsservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingcostsservice
  labels:
    app: shippingcostsservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingcostsservice
  template:
    metadata:
      labels:
        app: shippingcostsservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "shippingcostsservice"
        dapr.io/port: "80"
    spec:
      containers:
      - name: shippingcostsservice
        image: xpiritbv/dapr-demo-shippingcostsservice:43980340
        ports:
        - containerPort: 80
        imagePullPolicy: Always