apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jaegerzipkin
spec:
  type: exporters.zipkin
  metadata:
  - name: enabled
    value: "true"
  - name: exporterAddress
    value: "http://simplest-collector.observability.svc.cluster.local:9411/api/v2/spans"