name: shippingcostsservice-ci

on:
  push:
    paths: 
    - 'OrderApp/ShippingCostsService/**'
    - '.github/workflows/shippingcostsservice-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{DOCKERUSER}}
        password: ${{DOCKERPW}}

    - name: Build & Push the Docker image
      run: |
        docker build OrderApp \
                     -f OrderApp/ShippingCostsService/Dockerfile \
                     -t xpiritbv/dapr-demo-shippingcostsservice:$GITHUB_RUN_ID \
                     -t xpiritbv/dapr-demo-shippingcostsservice:latest
        docker push xpiritbv/dapr-demo-shippingcostsservice:$GITHUB_RUN_ID
      
